server:
  port: 6666
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: flzx_qc
    url: jdbc:mysql://localhost:3306/zbiti-frame?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
  redis:
    host: zbiti-redis
    port: 6379
    password: flzx_qc
  thymeleaf:
    prefix: /templates/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    loadbalancer:
      cache:
        enabled: false
